
name: idrs
description: iDRS app with final layout and camera support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  video_player: ^2.7.0
  flutter_colorpicker: ^1.0.3
  gallery_saver: ^2.3.2
  path_provider: ^2.0.15

flutter:
  uses-material-design: true
